### ISSUE TITLE
Make a release.

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/dotsAndBoxes#11]
@nswarup14 you might be interested. Thanks!

**Comment by ayushnawal** [comment]
@Aniket21mathur can you please guide me in resolving this issue?

**Comment by quozl** [comment]
https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#modifying-activities describes steps in making a release of an activity.

I've reassessed.  This activity;
* was released as [v3 in 2013](http://activities.sugarlabs.org/en-US/sugar/addon/4663) as a GTK 2 activity,
* was [ported to GTK 3](https://github.com/sugarlabs/dotsAndBoxes/commit/f6de4c1dc98112de8d88783b8f0d58891af5b62e)  and not released,
* has yet to be [ported to Python 3](https://github.com/sugarlabs/dotsAndBoxes/issues/12),
* has no release tags in git.

**Comment by Aniket21mathur** [comment]
@ayushnawal I would like to get a Python 3 ported version of the activity before making a release. Please go through the documentation as @quozl suggested.
